FORMAT: 1A
HOST: https://rt.ambientweather.net/

# Ambient Weather REST API

Access an Ambient Weather user's weather station data programmatically using our REST API

##### Authentication

Two API Keys are required for all REST API requests:

+ `applicationKey` - identifies the developer / application. To create an application key please login to your AmbientWeather.net account page (https://dashboard.ambientweather.net/account)
+ `apiKey` - grants access to past/present data for a given user's devices.  A typical consumer-facing application will initially ask the user to create an `apiKey` on their AmbientWeather.net account page (https://dashboard.ambientweather.net/account) and paste it into the app.  Developers for personal or in-house apps will also need to create an apiKey on their own account page.

##### Rate Limiting

API requests are capped at 1 request/second for each user's apiKey and 3 requests/second per applicationKey.  When this limit is exceeded, the API will return a 429 response code. Please be kind to our servers :)

##### Helper Libraries

+ Node.js - https://github.com/owise1/ambient-weather-api
+ PHP (Laravel) - https://github.com/Jafo232/ambient_api
+ Go - https://github.com/lrosenman/ambient
+ Python - https://github.com/avryhof/ambient_api
+ Python (asyncio) - https://github.com/bachya/aioambient
+ R - https://github.com/andrewflack/ambientweatheR
+ Java - https://github.com/rsv-code/ambient-weather-java
+ Swift - https://github.com/MikeManzo/SwiftyWeatherKit

##### Other Resources
+ API Wiki - https://github.com/ambient-weather/api-docs/wiki
+ This documentation's repository - https://github.com/ambient-weather/api-docs

## Devices [/v1/devices{?apiKey,applicationKey}]

### List User's Devices [GET]

Provides a list of the user's available devices along with each device's most recent data.

+ Parameters
  + applicationKey (required) - Application Key
  + apiKey (required) - API Key for user account

+ Response 200 (application/json)

        [
            {
                "macAddress": "00:00:00:00:00:00",
                "info": {
                  "name": "My Weather Station",
                  "location": "Home"
                },
                "lastData": {
                    "dateutc": 1515436500000,
                    "date": "2018-01-08T18:35:00.000Z",
                    "winddir": 58,
                    "windspeedmph": 0.9,
                    "windgustmph": 4,
                    "maxdailygust": 5,
                    "windgustdir": 61,
                    "winddir_avg2m": 63,
                    "windspdmph_avg2m": 0.9,
                    "winddir_avg10m": 58,
                    "windspdmph_avg10m": 0.9,
                    "tempf": 66.9,
                    "humidity": 30,
                    "baromrelin": 30.05,
                    "baromabsin": 28.71,
                    "tempinf": 74.1,
                    "humidityin": 30,
                    "hourlyrainin": 0,
                    "dailyrainin": 0,
                    "monthlyrainin": 0,
                    "yearlyrainin": 0,
                    "feelsLike": 66.9,
                    "dewPoint": 34.45380707462477
                }
            }
        ]

## Device Data [/v1/devices/{macAddress}{?apiKey,applicationKey,endDate,limit}]

+ Parameters
  + macAddress (required) - device Mac Address
  + apiKey (required) - API Key for user account
  + applicationKey (required) - Application Key
  + endDate (optional) - The most recent datetime. Results descend from there. If left blank, the most recent results will be returned.  Date format should be in milliseconds since the epoch or string representations outlined here: https://momentjs.com/docs/#/parsing/string/. Note: datetimes are stored in UTC.
  + limit (optional, number) - The maximum number of results to return (max: 288)
      + Default: 288


### Query Device Data [GET]

Fetch data for a given device. Data is stored in 5 or 30 minute increments. A list of all possible fields is here: https://github.com/ambient-weather/api-docs/wiki/Device-Data-Specs

+ Response 200  (application/json)

        [
            {
                "dateutc": 1515436500000,
                "date": "2018-01-08T18:35:00.000Z",
                "winddir": 58,
                "windspeedmph": 0.9,
                "windgustmph": 4,
                "maxdailygust": 5,
                "windgustdir": 61,
                "winddir_avg2m": 63,
                "windspdmph_avg2m": 0.9,
                "winddir_avg10m": 58,
                "windspdmph_avg10m": 0.9,
                "tempf": 66.9,
                "humidity": 30,
                "baromrelin": 30.05,
                "baromabsin": 28.71,
                "tempinf": 74.1,
                "humidityin": 30,
                "hourlyrainin": 0,
                "dailyrainin": 0,
                "monthlyrainin": 0,
                "yearlyrainin": 0,
                "feelsLike": 66.9,
                "dewPoint": 34.45380707462477
            }
        ]

# Group Ambient Realtime API

Access an Ambient Weather user's weather station data in realtime using our Realtime API


##### Authentication

You will be working with two types of keys when using the Realtime API:

+ `applicationKey` - identifies the developer / application. This key is passed to the server when you make the initial connection
+ `apiKey` - identifies a user. This key grants read-only access to all of the devices for a given user. It is used in the `subscribe` command (see below)

##### Websockets

The realtime API uses Websockets and is based on Socket.io (https://socket.io/). The easiest way to use the API is to use a Socket.io helper library. They are available in most languages.

Socket.io Endpoint: `https://rt.ambientweather.net/?api=1&applicationKey=....`

Note the query parameters `api=1` to identify the api version and `applicationKey=....` to identify your application

Upon successful connection, you'll send commands and listen for responses.


##### Helper Libraries

+ Node.js - https://github.com/owise1/ambient-weather-api

###### Command: connect

Connect to the Realtime API

###### Command: disconnect

Disconnect from the Realtime API

###### Command: subscribe

Listen for new data from all the devices for users' apiKeys.

command body - an object containing the property apiKeys that is an array of apiKeys:
```
{
    apiKeys:
        [
            'multiple',
            'apiKeys',
            'are fine'
        ]
}
```

###### Command: unsubscribe

Stop listening for new data from all the devices for users' apiKeys.

command body - an object containing the property apiKeys that is an array of apiKeys:
```
{
    apiKeys:
        [
            'multiple',
            'apiKeys',
            'are fine'
        ]
}
```


##### Event: subscribed

`subscribed` events are emitted after you send a `subscribe` or `unsubscribe` command. It will list all of the devices you are currently subscribed to and, if applicable, will return apiKeys that are not valid.

event body - an object containing one or more properties
+ `devices` - an array containing objects for all of the devices you are currently subscribed to
+ `invalidApiKeys` - an array of apiKeys that aren't valid

```
{
    "devices": [
        {
            "macAddress": "00:00:00:00:00:00",
            "info": {
                "name": "My Weather Station",
                "location": "Home"
                "address": "this_device_physical_street_address",
                "elevation": 60.72509002685547,
                "coords": {
                    "coords": {
                        "lat": xxx.xxxxxxx,
                        "lon": xxx.xxxxxxx
                    },
                "geo": {
                    "type": "Point",
                    "coordinates": [
                        xxx.xxxxxxx,
                        xxx.xxxxxxx
                    ]
                }
            },
            "lastData": {
                "dateutc": 1515436500000,
                "date": "2018-01-08T18:35:00.000Z",
                "winddir": 58,
                "windspeedmph": 0.9,
                "windgustmph": 4,
                "maxdailygust": 5,
                "windgustdir": 61,
                "winddir_avg2m": 63,
                "windspdmph_avg2m": 0.9,
                "winddir_avg10m": 58,
                "windspdmph_avg10m": 0.9,
                "tempf": 66.9,
                "humidity": 30,
                "baromrelin": 30.05,
                "baromabsin": 28.71,
                "tempinf": 74.1,
                "humidityin": 30,
                "hourlyrainin": 0,
                "dailyrainin": 0,
                "monthlyrainin": 0,
                "yearlyrainin": 0,
                "feelsLike": 66.9,
                "dewPoint": 34.45380707462477
                "deviceId": "this_devices_unique_device_id"
            },
            "apiKey": "the_apiKey_for_the_user_this_device_belongs_to"
        }
    ],
    "invalidApiKeys": [
            'an_api_key_that_is_not_any_good'
    ],
    "method:" "subscribe"
}
```

##### Event: data

`data` events are emitted when a device you are subscribed to sends new data. The data contains a `macAddress` property that you can use to match against the device list supplied by the `subscribed` event

event body - an object representing a device's data point

```
{
    "macAddress": "00:00:00:00:00:00",
    "dateutc": 1515436500000,
    "date": "2018-01-08T18:35:00.000Z",
    "winddir": 58,
    "windspeedmph": 0.9,
    "windgustmph": 4,
    "maxdailygust": 5,
    "windgustdir": 61,
    "winddir_avg2m": 63,
    "windspdmph_avg2m": 0.9,
    "winddir_avg10m": 58,
    "windspdmph_avg10m": 0.9,
    "tempf": 66.9,
    "humidity": 30,
    "baromrelin": 30.05,
    "baromabsin": 28.71,
    "tempinf": 74.1,
    "humidityin": 30,
    "hourlyrainin": 0,
    "dailyrainin": 0,
    "monthlyrainin": 0,
    "yearlyrainin": 0,
    "feelsLike": 66.9,
    "dewPoint": 34.45380707462477,
    "tz": "America/New_York"
    "device": {
        "macAddress": "00:00:00:00:00:00",
        "info": {
            "name": "My Weather Station",
            "coords": {
                "coords": {
                    lat": xxx.xxxxxxx,
                    lon": xxx.xxxxxxx
                },
            "address": "his_device_physical_street_address",
            "location": "Home",
            "elevation": 60.72509002685547,
            "geo": {
                "type": "Point",
                "coordinates": [
                    xxx.xxxxxxx,
                    xxx.xxxxxxx
                ]
            }
        },
        "lastData": {
           "dateutc": 1515436500000,
            "date": "2018-01-08T18:35:00.000Z",
            "winddir": 58,
            "windspeedmph": 0.9,
            "windgustmph": 4,
            "maxdailygust": 5,
            "windgustdir": 61,
            "winddir_avg2m": 63,
            "windspdmph_avg2m": 0.9,
            "winddir_avg10m": 58,
            "windspdmph_avg10m": 0.9,
            "tempf": 66.9,
            "humidity": 30,
            "baromrelin": 30.05,
            "baromabsin": 28.71,
            "tempinf": 74.1,
            "humidityin": 30,
            "hourlyrainin": 0,
            "dailyrainin": 0,
            "monthlyrainin": 0,
            "yearlyrainin": 0,
            "feelsLike": 66.9,
            "dewPoint": 34.45380707462477,
            "deviceId": "this_devices_unique_device_id",
            "tz": "America/New_York"
        },
        "apiKey": "the_apiKey_for_the_user_this_device_belongs_to"
    }
}
```